# Generated by Django 3.0 on 2022-02-17 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='ciudad')),
            ],
            options={
                'db_table': 'city',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel_usage_km', models.CharField(max_length=50, verbose_name='consumo de combustible')),
                ('spent_fuel', models.CharField(max_length=50, verbose_name='combustible consumido ')),
                ('distance_covered', models.CharField(max_length=50, verbose_name='Distancia recorrida')),
                ('current_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_location', to='fleet_admin.City')),
            ],
            options={
                'db_table': 'vehicle',
            },
        ),
        migrations.CreateModel(
            name='DistanceBethwenCities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.CharField(max_length=50, verbose_name='Distancia')),
                ('city_arrival', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city_arrival', to='fleet_admin.City')),
                ('city_origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city_origin', to='fleet_admin.City')),
            ],
            options={
                'db_table': 'dictance_city',
            },
        ),
    ]
